### ISSUE TITLE
Doesn't create MCPACK file

### ISSUE THREAD

**Issue by dsevvv** [agentdid127/RPC-Bedrock#8]
So I use Geyser to enable cross-play for me Java server.

To allow my Bedrock players to see my Java resource pack I have been looking for a tool exactly like this! You can imagine my delight when I came across your software. However, I need the java resource pack converted to a MCPACK file as this is how Geyser sends the resource pack to Bedrock users. 

I have no use for the converted zip, I need a MCPACK file.

Please help!

**Comment by CoryBorek** [comment]
I could probably write a solution to this quickly, but in the meantime, a `.mcpack` is essentially just a renamed `.zip` file. so just rename the zip file extension to `.mcpack`, and it should work!

**Comment by CoryBorek** [comment]
The issue should be fixed in the latest alpha release!

**Comment by dsevvv** [comment]
Sheesh AITE TYVM

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
